### ISSUE TITLE
Game failed while solving

### ISSUE THREAD

**Issue by SameplayerDE** [mrtenda/voltorbflipdotcom#12]
I filled in the numbers to solve the game and when it asked me what tile was at a specific position, I chose volt orb because I already have lost the game on the DS and just wanted to check if the site would solve the game correctly. So I chose volt orb and it told me I lost. IDK if this could be called a bug or a feature. I unsterdant the reason but would be cool if someone could use the solver to solve without failing

**Comment by mrtenda** [comment]
I would need to know what inputs you used to debug this further. I can't do anything more from here so closing this.
