### ISSUE TITLE
Feature request: Detect more invalid boards

### ISSUE THREAD

**Issue by Gudf** [mrtenda/voltorbflipdotcom#16]
Sometimes, the user may input a number incorrectly for one row or one column, such as in the following case, where the first column is supposed to be a 6/1. 
![Screenshot_20230424_222237](https://user-images.githubusercontent.com/28691694/234108897-d0539583-6bdf-43fc-87aa-e26848deb50e.png)
As you can see, currently the tool doesn't detect the error, but it should be quite easy to detect since in a valid board the numbers for the rows sum to the same values as the numbers for the columns.

**Comment by mrtenda** [comment]
Implemented! Thanks
<img width="641" alt="Screen Shot 2023-09-12 at 7 39 55 PM" src="https://github.com/mrtenda/voltorbflipdotcom/assets/1281326/0055602f-862b-4c4c-83f5-931075ddcf82">
