### ISSUE TITLE
Bug: Too early suggesting that a solution was found

### ISSUE THREAD

**Issue by joandrsn** [mrtenda/voltorbflipdotcom#17]
See the following image:

![image](https://github.com/mrtenda/voltorbflipdotcom/assets/5766695/41c83a12-c680-4538-ba78-f91e3c3d73d3)
There are still points missing from row 3 and 4.

**Comment by crimsonDestroyer** [comment]
I have also encountered this issue.
![image](https://github.com/mrtenda/voltorbflipdotcom/assets/34079063/e61214bc-b9ea-4bda-ab9a-ce526cbf536e)

**Comment by mrtenda** [comment]
Just tried to reproduce both of these cases and I'm not seeing this happen. See below screenshots.

Feel free to re-open this if you see it still happening.

<img width="599" alt="Screen Shot 2023-09-12 at 7 46 04 PM" src="https://github.com/mrtenda/voltorbflipdotcom/assets/1281326/6bebd40e-e0f0-433f-8ac2-f84f15ed6971">
<img width="606" alt="Screen Shot 2023-09-12 at 7 47 01 PM" src="https://github.com/mrtenda/voltorbflipdotcom/assets/1281326/d933aad5-c120-4314-a945-da56f9d2a7a4">

**Comment by crimsonDestroyer** [comment]
I attempted to re-create both mine and joandrsn's board states.
Theirs still occurs as they showed it.
![image](https://github.com/mrtenda/voltorbflipdotcom/assets/34079063/e1324e55-3aa2-4f92-8c6c-8bba325b8455)
Mine, however, is behaving differently each time, despite identical starting conditions, requesting different tiles each time and only sometimes declaring an early victory. Both of the following were created using the exact same input numbers, in accordance with the information shown in my original screenshot, and following the provided instructions.
![image](https://github.com/mrtenda/voltorbflipdotcom/assets/34079063/e8f8f3d0-c5f9-4dc9-8b82-3e7383a94ef1)
![image](https://github.com/mrtenda/voltorbflipdotcom/assets/34079063/e574272d-f32e-4248-8257-5cb58f79b354)
In all cases, the website requested the values of different tiles in different orders. Have you tried doing this multiple times and seeing if the result changes?

**Comment by mrtenda** [comment]
I've tried your first test case several times but I can't get the same result that you showed. See below screenshot.

However, I believe I may have actually fixed this bug last night (after your sent your last message): https://github.com/mrtenda/voltorbflipdotcom/commit/70f5f9e8df7c70140ee699afbbbf0faf2c51e831

The updated code is now deployed to voltorbflip.com, so If you're still seeing the issue there please let me know.

![image](https://github.com/mrtenda/voltorbflipdotcom/assets/1281326/d2bb84fc-5c42-47bc-a546-e0053abf415a)
