### ISSUE TITLE
Algorithm can tell me when it's just about 50:50

### ISSUE THREAD

**Issue by pascaldornfeld** [mrtenda/voltorbflipdotcom#3]
Hi, I like your calculator. Once I tried the same but I was stuck at the stochastics. I noticed that your program always recommends to take the field with the lowest probability of a 'bomb'. Sometimes the actual winrate is 50%. Often it is like: 2 fields that are either 'bomb' or '2' and the rest is 'bomb' or '1'. Usually every 'bomb' vs '1' decision is like 15% bomb so the algorithm tells me to take that risk. If you look on the whole field you see that everything comes down to which field is the '2' and it has a 50% chance. Is it possible to show this information to the user?

- One good solution is to just show, which field can have which values so I can see detect that situation myself.

- Another solution is to show a global calculated "winrate".

- Maybe it is a solution to just never recommend to open the '1' vs 'bomb'. You are taking a risk but you don't win any points with that. Rarely you get knowledge for other points >'1' with an sumed up lower risk. Do you? It has to be investigated if there are cases where it makes sense. If there aren't, just skip that recommendations and let it say "take the '2' or 'bomb' field with a chance of 50%". If there are, an algorithm can be implemented that calculates the usefulness of the recommendation in this case. Maybe a value like 'chances until a value >1 can be taken' can be helpful. Lets say we are at S, the '2' vs 'bomb' has a probability of X and is called T so it ultimatively is (S->T)=X. Now the '1' vs 'bomb' things are called A, B, C and so on. When you take the '1' vs 'bomb' things before the '2' vs 'bomb' it looks like (S->A->...->T)=X. If I am right the value X should stay the same and can help to say: "it's 50:50, so just stop".

When I say: '2' vs 'bomb' I mean all situations where you can pick a 'bomb' or a value >1, so 'bomb' vs '3' is included, etc.

**Comment by mrtenda** [comment]
Thanks for the detailed bug report. Yeah, I'm aware the choice of recommendations maybe should be changed. I'm not working on this project anymore, but feel free to submit a PR or fork it if you'd like to see this fixed.

**Comment by mattgriffin94** [comment]
I have a PR out to address the third bullet point. #5

**Comment by mrtenda** [comment]
PR accepted. Will close this after deploying the fix
