### ISSUE TITLE
Field does not get solved completely

### ISSUE THREAD

**Issue by pascaldornfeld** [mrtenda/voltorbflipdotcom#4]
Hi, in one game the field was not solved but the page said, it was.

![Bildschirmfoto vom 2020-04-19 21-45-04](https://user-images.githubusercontent.com/52472959/79698129-130c7200-8287-11ea-860f-125b0cb80eb8.png)

**Comment by pascaldornfeld** [comment]
same here

![Bildschirmfoto vom 2020-04-19 21-58-03](https://user-images.githubusercontent.com/52472959/79698384-dc375b80-8288-11ea-9cd2-53a4d37bb561.png)

**Comment by Novocastrian** [comment]
Same here as well: 
![image](https://user-images.githubusercontent.com/4601813/89099701-8dc35c80-d434-11ea-8b09-31bc7c766950.png)

For what it's worth, each step it asked me for the result, the answer was "1" except the last (6th) question, which was a 3.

**Comment by MrRedstoner** [comment]
For what it's worth I had solid luck just hitting restart and solve again

**Comment by MrRedstoner** [comment]
Welp, here we are then. Restart&solve didn't help, same for the next game, though a full reload (Ctrl+Shift+R in my case) did
![VoltorbFlip](https://user-images.githubusercontent.com/36436231/99180590-c1966980-2727-11eb-9a46-0e9084a37fd3.png)
no repeats since so far
